#! /bin/bash
set -e

TDIR=$(mktemp -d -t XXXXXX)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo ERROR: FAILED: "$@" >&2
    exit 1
}

trap failed ERR

# ======================================================================

export LD_LIBRARY_PATH="${ACMACSD_ROOT}/lib:${LD_LIBRARY_PATH}"
cd "$TESTDIR"
../dist/test-clone-projection test-2004-3.ace || failed test-clone-projection
./test-chart-create-from-scratch || failed test-chart-create-from-scratch
./test-modify-projection || failed test-modify-projection
./test-modify-plot-spec || failed test-modify-plot-spec
./test-convert || failed test-convert
./test-stress || failed test-stress
./test-titer-iterator || failed test-titer-iterator
./test-chart-modify || failed test-chart-modify

echo ../dist/test-chart-proportion-to-dontcare *.ace
../dist/test-chart-proportion-to-dontcare *.ace

echo test-chart-merge
../dist/test-chart-merge --ignore-passages 2004-01.ace 2004-02.ace 2004-3.ace
echo test-chart-merge-types-2-5
../dist/test-chart-merge-types-2-5 --ignore-passages 2004-01.ace 2004-02.ace

# ../bin/test-ace ./test.ace
# ../bin/acmacs-chart-info ./test.ace

# map-resolution-test acmacs.r/tests/testthat/2004-01.ace
# aw -u eu aw-map-resolution-test.py create chart_id=5cd2e2c12085ef3b493c6566 name='2004-01 eu test'
# aw -u eu aw-map-resolution-test.py json chain_id=5cd2e3ed2085ef3b49563b91 >/d/results-5cd2e3ed2085ef3b49563b91.json
# aw -u eu aw-map-resolution-test.py plot chain_id=5cd2e3ed2085ef3b49563b91 output=/d/map-res-test-5cd2e3ed2085ef3b49563b91 media=pdf size=300
# aw -u eu aw-map-resolution-test.py collect_all_errors chain_id=5cd2e3ed2085ef3b49563b91 >/d/all-errors-5cd2e3ed2085ef3b49563b91.json

# aw -u eu aw-map-resolution-test.py create chart_id=5cd2e2c12085ef3b493c6566 name='2004-01 eu test 4'  proportions_to_dont_care='[0.1]'
#  --> 5cd4596582f2aac1950107d7
# aw -u eu aw-chain.py tree id=5cd4596582f2aac1950107d7 all=true
#  aw -u eu aw-chain.py info id=
# aw -u eu aw-map-resolution-test.py plot chain_id=5cd4596582f2aac1950107d7 output=/d/map-res-test/4 media=pdf size=300
#  --> 
