#! /bin/bash

TDIR=$(mktemp -d -t XXXXXX)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED: "$@" >&2
    exit 1
}

trap failed ERR

# ======================================================================

if [[ "${T}" == "R" || "${T}" == "D" ]]; then
    if [[ -f /r/ramdisk-id && -d /r/T ]]; then
        export T=/r/T
    else
        export T="${TDIR}"
    fi
fi

cd "$TESTDIR"
for chart in test-2004-3.ace test.ace test-h1-2009.ace test-h1-2009-no-layers.ace; do
    echo test-chart-modify ${chart}
    ../dist/test-chart-modify ${chart} || failed ${TESTDIR}/../dist/test-chart-modify "${TESTDIR}/${chart}"
done
