#! /bin/bash

TDIR=$(mktemp -d)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED "$@" >&2
    exit 1
}

trap failed ERR

# ======================================================================

if [[ "${T}" == "R" || "${T}" == "D" ]]; then
    if [[ -f /r/ramdisk-id && -d /r/T ]]; then
        export T=/r/T
    else
        export T="${TDIR}"
    fi
fi

cd "$TESTDIR"
../dist/test-chart-modify ./test-2004-3.ace
../dist/test-chart-modify ./test.ace
