#! /bin/bash

TDIR=$(mktemp -d -t XXXXXX)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED: "$@" >&2
    exit 1
}

trap failed ERR

# ======================================================================

echo test-modify-projection

cd "$TESTDIR"
../dist/chart-modify-projection --points 0,3 --move-to 10,-10 test-2004-3.ace "${TDIR}/r1.ace" >/dev/null 2>&1 || failed chart-modify-projection --points 0,3 --move-to 10,-10 test-2004-3.ace "${TDIR}/r1.ace"
../dist/chart-layout test-2004-3.ace "${TDIR}/o.txt" 2>/dev/null
../dist/chart-layout "${TDIR}/r1.ace" "${TDIR}/r1.txt" 2>/dev/null
diff "${TDIR}/o.txt" "${TDIR}/r1.txt" >"${TDIR}/diff-1.txt" || true
cmp "${TDIR}/diff-1.txt" test-modify-projection.expected-1.diff || (echo '********************'; cat "${TDIR}/diff-1.txt"; echo '********************'; false)

../dist/chart-transformation test-2004-3.ace >"${TDIR}/test-2004-3.transformation.txt"
xz -dc test-2004-3.ace >"${TDIR}/orig.json"

../dist/chart-modify-projection --rotate-degrees 60 test-2004-3.ace "${TDIR}/r2.ace" >/dev/null 2>&1 || failed chart-modify-projection --rotate-degrees 60 test-2004-3.ace "${TDIR}/r2.ace"
../dist/chart-transformation "${TDIR}/r2.ace" >"${TDIR}/r2.transformation.txt"
diff "${TDIR}/test-2004-3.transformation.txt" "${TDIR}/r2.transformation.txt" >"${TDIR}/diff-2.txt" || true
cmp "${TDIR}/diff-2.txt" test-modify-projection.transformation-2.diff || (echo '********************'; cat "${TDIR}/diff-2.txt"; echo '********************'; false)
xz -dc "${TDIR}/r2.ace" >"${TDIR}/r2.json"
diff -I "\"\\?created\":" "${TDIR}/orig.json" "${TDIR}/r2.json" >"${TDIR}/diff-2.txt" || true
cmp "${TDIR}/diff-2.txt" test-modify-projection.expected-2.diff || (echo '********************'; cat "${TDIR}/diff-2.txt"; echo '********************'; false)

../dist/chart-modify-projection --flip-ew test-2004-3.ace "${TDIR}/r3.ace" >/dev/null 2>&1 || failed chart-modify-projection test-2004-3.ace
../dist/chart-transformation "${TDIR}/r3.ace" >"${TDIR}/r3.transformation.txt"
diff "${TDIR}/test-2004-3.transformation.txt" "${TDIR}/r3.transformation.txt" >"${TDIR}/diff-3.txt" || true
cmp "${TDIR}/diff-3.txt" test-modify-projection.transformation-3.diff || (echo '********************'; cat "${TDIR}/diff-3.txt"; echo '********************'; false)
xz -dc "${TDIR}/r3.ace" >"${TDIR}/r3.json"
diff -I "\"\\?created\":" "${TDIR}/orig.json" "${TDIR}/r3.json" >"${TDIR}/diff-3.txt" || true
cmp "${TDIR}/diff-3.txt" test-modify-projection.expected-3.diff || (echo; echo; diff -I "\"\\?created\":" "${TDIR}/orig.json" "${TDIR}/r3.json" && false)
