#! /bin/bash
set -e

TDIR=$(mktemp -d -t XXXXXX)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED "$@" >&2
    exit 1
}

trap failed ERR

# ======================================================================

echo test-titer-iterator

cd "$TESTDIR"
../dist/test-titer-iterator ./test-2004-3.ace
../dist/test-titer-iterator ./test.ace
