#! /bin/bash
. ./_functions

# ======================================================================

echo test-convert

cd "$TESTDIR"
../dist/chart-convert ./test-2004-3.ace "${TDIR}/r1.ace" >/dev/null 2>&1
../dist/chart-convert ./test-2004-3.ace "${TDIR}/orig.txt" >/dev/null || failed " ../dist/chart-convert ./test-2004-3.ace orig.txt"
../dist/chart-convert "${TDIR}/r1.ace" "${TDIR}/r1.txt" >/dev/null || failed " ../dist/chart-convert r1.ace r1.txt"
diff "${TDIR}/orig.txt" "${TDIR}/r1.txt" >"${TDIR}/diff-1.txt" || true
