#! /bin/bash
set -e

# TDIR=$(mktemp -d -t XXXXXX)
# TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED "$@" >&2
    exit 1
}

trap failed ERR

# ======================================================================

echo test-relax-seed

exit_code=0
declare -a seed_stress=( [0]=858.3172515667444 [1]=858.3172515666472 [2]=858.3172515667727 [3]=855.7830722734781 [4]=1025.6190297068617 [5]=856.3866009464115 [6]=843.3259591199982 [7]=853.5368824005341 [8]=1053.0096479184795 [9]=855.4332663447229 [10]=843.576595876454 )
for seed in "${!seed_stress[@]}"; do
    stress="$(../dist/chart-relax ./test-h1-2009.ace -d 2 --seed ${seed} | /usr/bin/awk '/>=none/ { print $2; }')"
    # echo "${stress} vs. expected ${seed_stress[$seed]}"
    if [[ "${stress}" != "${seed_stress[$seed]}" ]]; then
        echo "Stress difference for seed ${seed}: ${stress} vs. expected ${seed_stress[$seed]}" >&2
        exit_code=1
    fi
done
exit ${exit_code}
