#! /bin/bash
set -e

TDIR=$(mktemp -d -t XXXXXX)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED "$@" >&2
    exit 1
}

trap failed ERR

# ======================================================================

echo test-convert

cd "$TESTDIR"
../dist/chart-convert ./test-2004-3.ace "${TDIR}/r.ace" >/dev/null 2>&1
xz -dc ./test-2004-3.ace >"${TDIR}/orig"
xz -dc "${TDIR}/r.ace" | diff -I "\"\\?created\":" "${TDIR}/orig" -
