#! /bin/bash
set -e

# TDIR=$(mktemp -d)
TESTDIR=$(dirname $0)

# ======================================================================

# function on_exit
# {
#     rm -rf "$TDIR"
# }

# trap on_exit EXIT

function failed
{
    echo FAILED: "$@" >&2
    exit 1
}

trap failed ERR

# ======================================================================

echo test-chart-create-from-scratch
cd "$TESTDIR"
../dist/test-chart-create-from-scratch
