#! /bin/bash
set -e

TDIR=$(mktemp -d -t XXXXXX)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED "$@" >&2
    exit 1
}

trap failed ERR

# ======================================================================

echo test-stress

cd "$TESTDIR"
printf "  test-stress 1\n"
../dist/chart-stress --double --precision 6 ./test-2004-3.ace >"${TDIR}/test-2004-3.txt"
# 2>/dev/null
../dist/chart-stress --gradient-max --precision 6 ./test-2004-3.ace >>"${TDIR}/test-2004-3.txt"
# 2>/dev/null
diff "${TDIR}/test-2004-3.txt" test-stress-expected-1.txt 

printf "  test-stress 2\n"
../dist/chart-stress --double --precision 6 ./test.ace >"${TDIR}/test.txt"
# 2>/dev/null
../dist/chart-stress --gradient-max --precision 6 ./test.ace >>"${TDIR}/test.txt"
# 2>/dev/null
diff "${TDIR}/test.txt" test-stress-expected-2.txt
