#! /bin/bash
set -e

# TDIR=$(mktemp -d -t XXXXXX)
# TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED "$@" >&2
    exit 1
}

trap failed ERR

function abs
{
    [[ $[ $@ ] -lt 0 ]] && echo "$[ ($@) * -1 ]" || echo "$[ $@ ]"
}

if [[ "$HOSTNAME" == "i19" ]]; then
    threshold=5
else
    threshold=0
fi

# ======================================================================

echo test-relax-seed

exit_code=0
declare -a seed_stress=( [0]=858 [1]=858 [2]=858 [4]=1026 [5]=856 [6]=843 [8]=1053 [9]=855 [10]=844 [11]=857 [13]=860)
for seed in "${!seed_stress[@]}"; do
    stress="$(../dist/chart-relax ./test-h1-2009.ace -d 2 --seed ${seed} | /usr/bin/awk '/>=none/ { printf "%.0f", $2; }')"
    # echo diff $(abs $((stress - ${seed_stress[$seed]})))
    # echo "${stress} vs. expected ${seed_stress[$seed]}"
    if [[ $(abs $((stress - ${seed_stress[$seed]}))) -gt $threshold ]]; then
        echo "Stress difference for seed ${seed}: ${stress} vs. expected ${seed_stress[$seed]}" >&2
        exit_code=1
    fi
done
exit ${exit_code}
