#! /bin/bash
. ./_functions

# ======================================================================

echo test-modify-plot-spec

cd "$TESTDIR"
../dist/chart-modify-plot-spec --sera 4,5 --fill pink --size 25 ./test-2004-3.ace "${TDIR}/r1.ace" >/dev/null 2>&1
../dist/chart-convert ./test-2004-3.ace "${TDIR}/orig.txt" >/dev/null || failed " ../dist/chart-convert ./test-2004-3.ace orig.txt"
../dist/chart-convert "${TDIR}/r1.ace" "${TDIR}/r1.txt" >/dev/null || failed " ../dist/chart-convert r1.ace r1.txt"
diff "${TDIR}/orig.txt" "${TDIR}/r1.txt" >"${TDIR}/diff-1.txt" || true
cmp "${TDIR}/diff-1.txt" test-modify-plot-spec.expected-1.diff  || report_fail "test-modify-plot-spec" "${TDIR}/diff-1.txt" "${TDIR}/orig.txt" "${TDIR}/r1.txt"
