#include <iostream>
#include <iomanip>
#include <ctime>
#include <map>
#include <algorithm>

#include "acmacs-base/argc-argv.hh"
#include "acmacs-base/enumerate.hh"
#include "acmacs-base/string.hh"
#include "acmacs-chart/factory.hh"
#include "acmacs-chart/chart.hh"

// ----------------------------------------------------------------------

using fields_t = std::map<std::string, std::vector<std::string>>;

static void print_plot_spec(const argc_argv& args);
static std::map<std::string, size_t> field_max_length(const fields_t& aFields);

// ----------------------------------------------------------------------

int main(int argc, char* const argv[])
{
    int exit_code = 0;
    try {
        argc_argv args(argc, argv, {
                {"-h", false},
                {"--help", false},
                {"-v", false},
                {"--verbose", false}
        });
        if (args["-h"] || args["--help"] || args.number_of_arguments() != 1) {
            std::cerr << "Usage: " << args.program() << " [options] <chart-file>\n" << args.usage_options() << '\n';
            exit_code = 1;
        }
        else {
            print_plot_spec(args);
            //     const auto num_digits = static_cast<int>(std::log10(std::max(antigens->size(), sera->size()))) + 1;
            //     for (auto [ag_no, antigen]: acmacs::enumerate(*antigens)) {
            //         std::cout << "AG " << std::setw(num_digits) << ag_no << " " << string::join(" ", {antigen->name(), string::join(" ", antigen->annotations()), antigen->reassortant(), antigen->passage(), antigen->date(), string::join(" ", antigen->lab_ids())}) << '\n';
            //     }
            //     for (auto [sr_no, serum]: acmacs::enumerate(*sera)) {
            //         std::cout << "SR " << std::setw(num_digits) << sr_no << " " << string::join(" ", {serum->name(), string::join(" ", serum->annotations()), serum->reassortant(), serum->passage(), serum->serum_id(), serum->serum_species()}) << '\n';
            //     }
            // }
        }
    }
    catch (std::exception& err) {
        std::cerr << "ERROR: " << err.what() << '\n';
        exit_code = 2;
    }
    return exit_code;
}

// ----------------------------------------------------------------------

void print_plot_spec(const argc_argv& args)
{
    auto chart = acmacs::chart::factory(args[0], false);
    auto antigens = chart->antigens();
    auto sera = chart->sera();
    auto plot_spec = chart->plot_spec();
    auto now = std::time(nullptr);

    auto bool_to_string = [](bool b) -> std::string { return b ? "True" : "False"; };

    fields_t antigen_fields;
    for (auto [ag_no, antigen]: acmacs::enumerate(*antigens)) {
        antigen_fields["I"].push_back(std::to_string(ag_no));
        antigen_fields["name"].push_back(antigen->name());
        antigen_fields["reassortant"].push_back(antigen->reassortant());
        antigen_fields["annotations"].push_back(antigen->annotations().join());
        antigen_fields["passage"].push_back(antigen->passage());
        auto style = plot_spec->style(ag_no);
        antigen_fields["fill_color"].push_back(style->fill());
        antigen_fields["outline_color"].push_back(style->outline());
        antigen_fields["outline_width"].push_back(std::to_string(style->outline_width()));
        antigen_fields["size"].push_back(std::to_string(style->size()));
        antigen_fields["shown"].push_back(bool_to_string(style->shown()));
        antigen_fields["aspect"].push_back(std::to_string(style->aspect()));
        antigen_fields["rotation"].push_back(std::to_string(style->rotation()));
        antigen_fields["shape"].push_back(style->shape());
            // drawing_level="66"
            // label=""
            // label_color=""
            // label_font_face=""
            // label_font_slant="normal"
            // label_font_weight="normal"
            // label_position_x="0.0"
            // label_position_y="1.0"
            // label_rotation="0.0"
            // label_shown="True"
            // label_size="1.0"
            // show_label="1"
    }
    auto antigen_field_lengths = field_max_length(antigen_fields);

    std::cout << "plot_style version 1" << '\n'
              << "# generated by chart-plot-spec on " << std::put_time(std::localtime(&now), "%c %Z") << '\n'
              << "#\n# Antigens\n#\n";
    for (size_t ag_no = 0; ag_no < chart->number_of_antigens(); ++ag_no) {
        std::cout << "T=\"AG\"";
        for (std::string field_name: {"I", "name", "reassortant", "annotations", "passage", "fill_color", "outline_color", "outline_width", "size", "shown", "aspect", "rotation", "shape"}) {
            const std::string value = field_name + "=\"" + antigen_fields[field_name][ag_no] + '"';
            std::cout << ' ' << std::left << std::setw(static_cast<int>(antigen_field_lengths[field_name] + field_name.size() + 3)) << value;
        }
        std::cout << '\n';
    }
            // const auto number_of_points = chart->number_of_antigens() + chart->number_of_sera();

} // print_plot_spec

// ----------------------------------------------------------------------

std::map<std::string, size_t> field_max_length(const fields_t& aFields)
{
    std::map<std::string, size_t> result;
    for (auto [name, values]: aFields) {
        result[name] = std::max_element(std::begin(values), std::end(values), [](const auto& a, const auto& b) { return a.size() < b.size(); })->size();
    }
    return result;
}

// ----------------------------------------------------------------------
/// Local Variables:
/// eval: (if (fboundp 'eu-rename-buffer) (eu-rename-buffer))
/// End:
